/** Per-asset MuAPI prompts (subject only — STYLE_PREFIX added by pipeline). */

export const PROP_PROMPTS = {
  flower_red: 'single tiny red wildflower, one green stem only, NO bushes NO ground',
  flower_yellow: 'single tiny yellow wildflower, one green stem only, NO bushes NO ground',
  flower_white: 'single tiny white daisy flower, one green stem only, NO bushes NO ground',
  flower_pink: 'single tiny pink flower, one green stem only, NO bushes NO ground',
  bush_small: 'small round green bush shrub',
  bush_large: 'large round leafy green bush',
  rock_small: 'small gray beach rock pebble',
  rock_large: 'large gray boulder rock',
  shell: 'pink spiral seashell',
  starfish: 'cute orange starfish',
  grass_tuft: 'small clump of green grass blades',
  mushroom: 'red cap white spots mushroom',
  clover: 'four leaf green clover',
  fern: 'green fern frond plant',
  pebble: 'tiny round gray pebble stone',
  driftwood: 'piece of brown driftwood log',
  coral_piece: 'single tiny pink coral branch on sand, underwater reef decor only, NO grass NO island NO platform NO house',
  lily: 'green lily pad with small white flower',
  tulip: 'red tulip flower with stem',
  daisy: 'white daisy flower with yellow center',
  tree_oak: 'oak tree top-down, round green canopy brown trunk, tall',
  tree_pine: 'pine tree top-down, triangular dark green, tall',
  tree_palm: 'palm tree top-down, green fronds brown trunk, tall',
  tree_apple: 'apple tree top-down, green canopy with red apples',
  tree_cherry: 'cherry blossom tree top-down, pink flowers green leaves',
  crate: 'wooden storage crate box',
  barrel: 'wooden barrel',
  bucket_item: 'metal water bucket',
  shovel: 'garden shovel tool',
  fork_tool: 'garden pitchfork tool',
  sign_post: 'wooden sign post plank',
  lantern: 'hanging oil lantern lamp',
  fence: 'wooden fence segment',
  fence_corner: 'wooden fence corner post',
  umbrella: 'beach umbrella striped',
  chair: 'wooden chair',
  lounger: 'wooden beach lounger chair side view',
  rope_coil: 'coiled hemp rope',
  sack: 'burlap sack bag',
  watering_can: 'green watering can',
  bottle: 'glass bottle',
  milk_pail: 'metal milk pail bucket',
  stool: 'small wooden stool',
  wheelbarrow: 'wooden wheelbarrow',
  hay_bale: 'rectangular hay bale',
  light_string: 'string of festive round lights horizontal',
  well: 'stone water well sprite top-down with wooden roof, NO grass NO platform',
  house_red: 'tiny cottage building sprite top-down, red roof white walls brown door, NO trees NO grass NO platform',
  house_blue: 'tiny cottage building sprite top-down, blue roof white walls brown door, NO trees NO grass NO platform',
  house_green: 'tiny cottage building sprite top-down, green roof white walls brown door, NO trees NO grass NO platform',
  house_yellow: 'tiny cottage building sprite top-down, yellow roof white walls brown door, NO trees NO grass NO platform',
  barn: 'red wooden barn building sprite top-down, large roof, NO grass NO platform',
  shop: 'colorful shop building sprite top-down with striped awning, NO grass NO platform',
};

export const UI_PROMPTS = {
  brush: 'paint brush tool icon',
  line: 'line draw tool icon',
  rect: 'rectangle shape tool icon',
  bucket: 'paint bucket fill tool icon',
  eraser: 'eraser tool icon',
  dropper: 'color picker eyedropper tool icon',
  hand: 'hand grab pan tool icon',
  land: 'island land terrain tab icon, green hill',
  decor: 'flower decoration tab icon',
  props: 'hammer tools props tab icon',
  world: 'globe world settings tab icon',
  map: 'treasure map tab icon',
  help: 'question mark help tab icon',
  settings: 'gear cog settings icon',
  pause: 'pause button icon',
  play: 'play triangle icon',
  eye: 'open eye visibility icon',
  camera: 'camera photo screenshot icon',
  water: 'water wave blue tile icon',
  sand: 'sand beach tile icon',
  grass: 'grass green tile icon',
  path: 'dirt path trail tile icon',
  bridge: 'wooden bridge tile icon',
  cliff: 'rock cliff tile icon',
  undo: 'curved undo arrow icon',
  redo: 'curved redo arrow icon',
  clear: 'trash clear delete icon',
  zoom: 'magnifying glass zoom icon',
  size: 'resize arrows size icon',
  space: 'four direction arrows move icon',
  villager: 'cute villager person icon',
  fish: 'small fish icon',
  whale: 'whale icon',
  ship: 'sailing ship boat icon',
  foam: 'water foam splash icon',
  repop: 'refresh repopulate circular arrows icon',
};

export const ENTITY_PROMPTS = {
  villager: 'ONE tiny pixel art HUMAN villager character sprite, full body top-down, red shirt blue pants brown hair, walking pose, MUST be a person NOT a house NOT a building',
  fish: 'small tropical orange fish top-down swimming',
  whale: 'blue whale top-down in water',
  shark: 'gray shark top-down',
  orca: 'orca killer whale black white top-down',
  swordfish: 'swordfish top-down with long bill',
  rowboat: 'small wooden rowboat top-down',
  galleon: 'pirate galleon sailing ship top-down with sails',
  spray: 'whale water spray splash spout',
};

export const STYLE_BOARD_PROMPT =
  'Style reference sheet for island builder game. Show samples in one image: ' +
  'red flower, oak tree, red roof cottage, villager, orange fish, grass tile, sand tile. ' +
  'Consistent pixel art style, white background grid layout.';

export const LOGO_PROMPT =
  'Game logo "Isle BUILDER" tropical island builder. Yellow pixel text, palm trees, ' +
  'small island with huts below text, dark blue background, retro pixel art style.';